native ESM + update dependencies
epicweb-dev/advanced-react-patterns pull request #118
Opened 2023-06-11 10:38 UTC by onemen

@kentcdodds 

Some tests are not ready, but they where not ready before this PR.

2023-06-12 18:48 UTC, kentcdodds requested changes
Thanks! Just two things.

2023-06-12 18:48 UTC, kentcdodds commented on package.json
> +  ],
I don't think we need this in this project because those directories don't have package.json files in them.

2023-06-12 18:48 UTC, kentcdodds commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
I think we can delete this now that we have the app that will do this for us.

2023-06-12 19:13 UTC, onemen commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
I did not test any of the scripts..

now i get `Cannot find package 'inquirer' imported ` ... did you ever have 'inquirer' installed, what the diff used for?

2023-06-12 19:19 UTC, onemen commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
you mean delete `diff.js`

2023-06-12 19:31 UTC, kentcdodds commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
Yup

2023-06-12 20:34 UTC, onemen commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
i'm not sure `remove-ts` will work anymore all import for internal file contain .ts or .tsx extension

2023-06-12 20:42 UTC, kentcdodds commented on scripts/diff.js
> -const { spawnSync } = require('child_process')
True. Let's worry about that later. I'm not actively working on this workshop myself anyway so I'll defer to the person who plans to do this.

2023-06-13 13:22 UTC, onemen commented
its ready

2023-06-13 14:46 UTC, kentcdodds approved these changes
Thanks!

2023-06-13 14:49 UTC, merged